// Research fields offered in the search facet, ordered by verified-paper count
// (June 2026 snapshot of the ~440k corpus). A live facet count over the
// unnested fields array is too slow to run per request, so this list is
// precomputed; regenerate it after a bulk reload if the distribution shifts.
export const TOP_FIELDS = [
  "Physical Sciences",
  "Social Sciences",
  "Health Sciences",
  "Medicine",
  "Life Sciences",
  "Engineering",
  "Agricultural and Biological Sciences",
  "Genetics",
  "Artificial intelligence",
  "Environmental Science",
  "Internal medicine",
  "Computer Science",
  "Environmental health",
  "Nursing",
  "Economic growth",
  "Law",
  "Biochemistry, Genetics and Molecular Biology",
  "Business, Management and Accounting",
  "Ecology",
  "Plant Science",
  "Economics, Econometrics and Finance",
  "Sociology and Political Science",
  "Immunology",
  "Microbiology",
  "Nanotechnology",
  "Materials Science",
  "Neuroscience",
  "Pharmacology",
  "Psychology",
  "Biotechnology",
  "Food Science",
  "Chemistry",
  "Mathematics",
  "Bioinformatics",
  "Dentistry",
  "Veterinary",
] as const;
